### PR TITLE
Adding travis config

### LINKED ISSUE #343: Adding travis CI configuration
I would like to work on this issue :)

### PR DESCRIPTION
**Pull request by iFlameing**
Fixes #343

### CODE REVIEW

**Comment by iFlameing** [comment]
If anyone connects this repository to Travis. I can see if this configuration is working fine or not?

**Comment by iFlameing** [comment]
@therewasaguy can you review this?

**Comment by therewasaguy** [comment]
thank you, @iFlameing, this'll be great!

I don't have owner permissions for Processing or for this repo, so I can't add it to travis-ci.org. @lmccart are you able to grant me permission or help with this?

**Comment by lmccart** [comment]
this is great. I need to do some work to look into our travis status, right now it's spread across https://travis-ci.com and https://travis-ci.org and I need to sort and consolidate that. so it may be a while, but once I've got that set I will add in p5.js-sound and see if I can also give you access @therewasaguy. thanks for your patience :)

**Comment by therewasaguy** [comment]
sounds good, thanks @lmccart ! This'll be good to set up when you get a chance, no rush.

**Comment by therewasaguy** [comment]
closed with https://github.com/processing/p5.js-sound/pull/355

**Pull request closed without merging**
