### PR TITLE
Correct typo

### LINKED ISSUE #634: Typo
There's a typo in the reference here:
https://p5js.org/reference/#/p5.Panner3D
"Connect an audio sorce"
Have a nice day

### PR DESCRIPTION
**Pull request by lf32**
I regenerated the library files after correcting the typo.

This commit fixes #634 and also replaces all the files in `lib/` directory with the latest code.

### CODE REVIEW

**Comment by lf32** [comment]
I have `git reset` my commit which includes change for fixing the typo as well as the generated lib files.

**Review by davepagurek — APPROVED** [review]
Thanks!

**Comment by lf32** [comment]
Thanks for the merge!

I have a question, why aren't the lib/ files regenerated till now?. Can I create a PR on this? Regenerate the `p5.sound.js` and `p5.sound.min.js`?

**Comment by davepagurek** [comment]
I think it's alright that they aren't regenerated in PRs, as it means the code changes are duplicated twice in the diff (once in the source files and another time in the lib folder.) [Rebuilding the lib files is part of the release process](https://github.com/processing/p5.js-sound/wiki/Releasing-a-new-version-of-p5.sound-library) so when we release a new version of the library, the changes will get build and added to lib then.

**Comment by lf32** [comment]
Ok, sounds cool!

**Pull request merged**
