### PR TITLE
setPitch_example

### PR DESCRIPTION
**Pull request by Nitesh639**
Regarding: Example for setPitch() #703  issue.

### CODE REVIEW

**Review by davepagurek — COMMENTED** [review]
This is a great example! Before merging, we just need to clean up the code formatting a bit -- right now it's a bit inconsistent. The rest of the codebase uses two-space indents, and has spaces around curly braces (`function preload() {` instead of `function preload(){`)

**Comment by davepagurek** [comment]
Thanks for the changes! I think there are still some more spacing changes that we need, as setup and draw are indented further than preload, and the closing curly braces are indented further than the f in `function`.

**Comment by Nitesh639** [comment]
I have made many changes regarding the spacing. @davepagurek, Please take a view at it. I think you will be happy after this.

**Review by davepagurek — APPROVED** [review]
Looks great!

**Comment by Nitesh639** [comment]
Thank you.

**Pull request merged**
