### PR TITLE
fixed abnormal behaviour of audio output in p5.signal example

### LINKED ISSUE #471: Sound starts to play when user visits the page , without users consent!
This is very annoying and horrible that when you visit https://p5js.org/reference/#/p5.Signal
there is sudden start of signals out of speakers !   :grimacing: 
a user consent is needed to play the signal !

* In  firefox version 75 it occurs  everytime , the link is visited !
* In chrome also  it is witnessed more often !

### PR DESCRIPTION
**Pull request by endurance21**
fixes #471 

before :
 `carrier.start()`  was placed inside setup function, and as soon as the script get rendered , user hears a all of a sudden sound of carrier node without the user consent :grimacing: !! 

after:
`carrier.start()` has been placed inside the `canvasPressed()` which ensures that output signal is heard by user when it Presses the canvas ! :grinning:

### CODE REVIEW

**Comment by endurance21** [comment]
@therewasaguy @montoyamoraga  
please review this PR !!

**Comment by montoyamoraga** [comment]
@endurance21 at the right side of the repo i have the option to ask for review, i am going to add myself, do you have that option? just wondering, so that it is easier than tagging.
also, it is easy to miss notifications, we do our best to review them, tag me anytime you need, best!

**Comment by endurance21** [comment]
@montoyamoraga i do see them, but i am not able to either assign myself or ask for review, i am wondering may be i don't have enough permissions😬

**Comment by endurance21** [comment]
@montoyamoraga 
aha , that's more nicer way to do that !  :grin: 
also ,  whenever mouse is Realeased we have to make `hasStarted   =  false `

**Comment by endurance21** [comment]
@montoyamoraga  
applied the changes ! :relaxed:

**Comment by montoyamoraga** [comment]
@endurance21 let me know if it makes sense and if it works please, thank you!
i hadn't used these features for reviewing here on GitHub so i am also learning :)

**Comment by endurance21** [comment]
@montoyamoraga 
1. if you are asking `hasStarted = false` ? , ya sure , we can  sure initilize the boolean at the declaration time !!
2. and yes i agree on it ! , it must be started only once !  i have tested it too, it works fine

**Comment by montoyamoraga** [comment]
@endurance21 thank you!

yes, i mean having two separate lines like this:

let carrier, modulator;
let hasStarted = false;

**Comment by endurance21** [comment]
@montoyamoraga 
ya that is more intuitive and readable , but i was kind'a avoiding use of multiple let :sweat_smile: 
but i think we should go with you idea ! :grinning:

**Comment by montoyamoraga** [comment]
@endurance21 it's a matter of style and use,
i always use one line for every variable declaration,
i'm not sure if we have a formal style guide for p5.js examples, 
maybe we should, maybe it's too much :)

**Comment by endurance21** [comment]
Infact same type of variables must be declared at same line, it enhances code readability 😎

**Pull request merged**
