### PR TITLE
added deprecation handling for p5.Signal

### PR DESCRIPTION
**Pull request by endurance21**

### CODE REVIEW

**Review by montoyamoraga — COMMENTED** [review]
hi @endurance21, your pull request looks correct to me,
but i don't know how to be build it or test it, could you please
tag other people who participated in the original issue? thanks :)

**Comment by endurance21** [comment]
@montoyamoraga
btw i have checked this one , and it is working fine :100:

**Comment by endurance21** [comment]
we can got with it

**Comment by endurance21** [comment]
@therewasaguy  please, have a look at it

**Review by therewasaguy — APPROVED** [review]
Nice solution! This could be a good foundation for deprecating more parts of the API in the future.

**Pull request merged**
