### PR TITLE
Added saveSoundToBlob() to soundRecorder.js

### PR DESCRIPTION
**Pull request by wahengchang**
as my need is recording sound by microphone, then appending it to DOM for preview before it is downloaded. a temporary blob url is the choice.

### CODE REVIEW

**Comment by therewasaguy** [comment]
thank you @wahengchang ! This will close https://github.com/processing/p5.js-sound/issues/257

**Comment by therewasaguy** [comment]
as part of a related issue (https://github.com/processing/p5.js-sound/issues/314) we may want to move these away from the p5.prototype to the SoundFile

**Comment by wahengchang** [comment]
@therewasaguy , when can I use the new version which included this Pull-Request ?
I need it desperately

**Comment by therewasaguy** [comment]
@wahengchang you can use it now by compiling p5 sound from source, and it will be included in the next release of p5.js, tho I'd like to move this (and saveSound) to p5.SoundFile / p5.AudioIn, before we make it part of the official API. Let me know if you have any thoughts on that, I'm about to take a look!

**Comment by therewasaguy** [comment]
^ https://github.com/processing/p5.js-sound/pull/315 would move `saveBlob` to SoundFile. I think that's the best home for this method?

**Comment by wahengchang** [comment]
👍

**Pull request merged**
