### PR TITLE
Modification added for the clarification of the vol parameter in the effect.js amp() function

### PR DESCRIPTION
**Pull request by parulpriyedarshani**
Solved issue #421 
Added documentation for the clarification of the vol parameter of the amp() function of p5.effect component.

### CODE REVIEW

**Comment by AkshJain99** [comment]
@parulpriyedarshani  I think you did some mistake 
Actually you have rebased the last commit of your another PR with this PR
Due to branch changes
It will be great If you will once have a look

**Comment by AkshJain99** [comment]
Now its fine @parulpriyedarshani now its fine
:+1;

**Comment by AkshJain99** [comment]
Now its fine @parulpriyedarshani  :+1:

**Comment by therewasaguy** [comment]
closing for now, feel free to re-open if you address the PR review comments and thank you @parulpriyedarshani

**Pull request closed without merging**
