### PR TITLE
(Docs): Improved docs and updated info for repo visitors

### PR DESCRIPTION
**Pull request by Abhijay007**
Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>

Update information in the readme, for the newcomers and project visitors, updated and added links to p5.js social communities.

### CODE REVIEW

**Comment by Abhijay007** [comment]
@davepagurek I have added some information badges related to the repo, and also added a link to the discord community as discussed on discord, the discord badge doesn't seem to fetch the number of community members, it is showing "widget disabled error", you might need to enable that in the discord channel, here is the guide to do that same : https://vimeo.com/364220040

**Comment by davepagurek** [comment]
Thanks @Abhijay007, this looks great! I'm just asking the mods of the discord to see if this is a setting we feel comfortable turning on. If we don't (which I imagine would only be because this allows non-members to potentially see online users), is there a badge we can use that only needs the server's signup link without full widget permissions?

**Comment by Abhijay007** [comment]
> Thanks @Abhijay007, this looks great! I'm just asking the mods of the discord to see if this is a setting we feel comfortable turning on. If we don't (which I imagine would only be because this allows non-members to potentially see online users), is there a badge we can use that only needs the server's signup link without full widget permissions?

I agree with the same that this might allow non-members to see online users, and that might not be approved,  but I tried different ways to add links to the community for the discord or to show a "join chat" link or something (just like we have for Gitter), but not able to find anything around it as most badge asks for different permissions, if it is not permitted then we can do one thing we can just add a simple discord badge and add "invite link to the community" on the same, as suggested by you, but still not sure about signup link.

**Comment by Abhijay007** [comment]
@davepagurek can update on the discord widget activation?

**Comment by davepagurek** [comment]
Just messaged the mods again to try to get some consensus to see if we can turn this on! I'll get back to you soon.

**Comment by Abhijay007** [comment]
> Just messaged the mods again to try to get some consensus to see if we can turn this on! I'll get back to you soon.

Hi @davepagurek any updates on this? should I replace that chat widget?

**Comment by davepagurek** [comment]
Sorry for the delay! Out of the mods who knew enough to comment, they were ok with it, but we didn't have enough who knew enough to comment for us to have a majority of mods. So maybe for now we should just replace it with a link, and we can perhaps revisit this again later.

**Review by montoyamoraga — APPROVED** [review]
awesome, thanks!
i went through this conversation and i think the additions are great, so i merged it!

**Pull request merged**
